package:
  name: 'conda_build_fort'
  version: '0.0.1'

source:
  path: ../

build:
  number: 0
  skip: True # [py<35]

requirements:
  run:
    - python
    - {{ pin_compatible('numpy') }}
  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python
    - setuptools
    - numpy-devel
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]

test:
  imports:
    - conda_build_fort
