package:
  name: 'pywasp_flow'
  version: '0.5'

source:
  path: ../

build:
  number: 0
  skip: True # [py<35]
  script: python setup.py install

requirements:
  run:
    - python
    - pywasp =0.5
    - {{ pin_compatible('numpy') }}
    - gdal>=2.0.0
    - lxml
    - matplotlib
    - netCDF4
    - scipy
    - pandas
    - pyproj
    - xarray
    - rasterio
    - shapely
  host:
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - python
    - setuptools
    - numpy >=1.16,<2.0.a0
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]

test:
  imports:
    - pywasp_flow
